name: MSBuild

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Echo
      run: echo "Deploying to production server on branch $GITHUB_REF"
